package com.example.appsteam

object GameRepository {

    val allGames: List<Game> = listOf(
        Game(
            id = "cs2",
            title = "Counter-Strike 2",
            price = "Grátis",
            review = "Extremamente Positivas",
            imageResId = R.drawable.game_cs2,
            bannerResId = R.drawable.game_cs2,
            tags = listOf("FPS", "Competitive", "Team-Based", "Action", "Multiplayer"),
            description = "Durante mais de duas décadas, o Counter-Strike ofereceu uma experiência competitiva de nível de elite. Agora, o próximo capítulo da saga CS está prestes a começar com o Counter-Strike 2.",
            isOwned = true,
            isInstalled = true,
            hoursPlayed = "842 hrs",
            isFeatured = true,
            becausePlayed = true
        ),
        Game(
            id = "dota2",
            title = "Dota 2",
            price = "Grátis",
            review = "Muito Positivas",
            imageResId = R.drawable.game_dota2,
            bannerResId = R.drawable.game_dota2,
            tags = listOf("MOBA", "Competitive", "Strategy", "Team-Based", "Multiplayer"),
            description = "Todos os dias, milhões de jogadores em todo o mundo entram na batalha como um dos mais de uma centena de heróis do Dota em um confronto entre duas equipes de 5 jogadores.",
            isOwned = true,
            isInstalled = false,
            hoursPlayed = "310 hrs",
            isFeatured = true,
            becausePlayed = true
        ),
        Game(
            id = "pubg",
            title = "PUBG: BATTLEGROUNDS",
            price = "Grátis",
            review = "Ligeiramente Positivas",
            imageResId = R.drawable.game_pubg,
            bannerResId = R.drawable.game_pubg,
            tags = listOf("Battle Royale", "FPS", "Survival", "Action", "Multiplayer"),
            description = "Jogue PUBG: BATTLEGROUNDS de graça. Pouse em locais estratégicos, saqueie armas e suprimentos e sobreviva para se tornar a última equipe de pé.",
            isOwned = true,
            isInstalled = false,
            hoursPlayed = "115 hrs"
        ),
        Game(
            id = "apex",
            title = "Apex Legends",
            price = "Grátis",
            review = "Muito Positivas",
            imageResId = R.drawable.game_apex,
            bannerResId = R.drawable.game_apex,
            tags = listOf("Battle Royale", "FPS", "Team-Based", "Action", "Competitive"),
            description = "Conquiste com estilo em Apex Legends, um jogo de tiro grátis onde personagens lendários com habilidades poderosas se unem para lutar por fama e fortuna.",
            isOwned = true,
            isInstalled = false,
            hoursPlayed = "92 hrs"
        ),
        Game(
            id = "tf2",
            title = "Team Fortress 2",
            price = "Grátis",
            review = "Extremamente Positivas",
            imageResId = R.drawable.game_tf2,
            bannerResId = R.drawable.game_tf2,
            tags = listOf("FPS", "Team-Based", "Action", "Multiplayer", "Competitive"),
            description = "Nove classes distintas fornecem uma ampla gama de habilidades táticas e personalidades. Constantemente atualizado com novos modos de jogo, mapas, equipamentos e chapéus!",
            isOwned = true,
            isInstalled = true,
            hoursPlayed = "520 hrs"
        ),
        Game(
            id = "unturned",
            title = "Unturned",
            price = "Grátis",
            review = "Muito Positivas",
            imageResId = R.drawable.game_unturned,
            bannerResId = R.drawable.game_unturned,
            tags = listOf("Zombies", "Survival", "Open World", "Multiplayer", "Crafting"),
            description = "Você é um dos poucos sobreviventes em ruínas infestadas por zumbis. Trabalhe com seus amigos e crie alianças para continuar entre os vivos.",
            isOwned = true,
            isInstalled = true,
            hoursPlayed = "64 hrs"
        ),
        Game(
            id = "cyberpunk",
            title = "Cyberpunk 2077",
            price = "R$ 99,95",
            originalPrice = "R$ 199,90",
            discountPercent = "-50%",
            review = "Muito Positivas",
            imageResId = R.drawable.game_cyberpunk,
            bannerResId = R.drawable.game_cyberpunk,
            tags = listOf("RPG", "Open World", "Sci-Fi", "Action", "Singleplayer"),
            description = "Cyberpunk 2077 é um RPG de ação e aventura em mundo aberto ambiente na megalópole de Night City, onde você joga como um mercenário cyberpunk.",
            isOwned = true,
            isInstalled = true,
            hoursPlayed = "88 hrs",
            isFeatured = true,
            isDiscounted = true,
            becausePlayed = true
        ),
        Game(
            id = "elden_ring",
            title = "Elden Ring",
            price = "R$ 229,90",
            review = "Extremamente Positivas",
            imageResId = R.drawable.game_elden_ring,
            bannerResId = R.drawable.game_elden_ring,
            tags = listOf("RPG", "Open World", "Action", "Dark Fantasy", "Competitive"),
            description = "LEVANTE-SE, MACULADO. Um RPG de ação e fantasia em um mundo criado por Hidetaka Miyazaki e George R. R. Martin.",
            isOwned = true,
            isInstalled = false,
            hoursPlayed = "140 hrs",
            isFeatured = true
        ),
        Game(
            id = "bg3",
            title = "Baldur's Gate 3",
            price = "R$ 199,99",
            review = "Extremamente Positivas",
            imageResId = R.drawable.game_bg3,
            bannerResId = R.drawable.game_bg3,
            tags = listOf("RPG", "Strategy", "Turn-Based", "Co-op", "Open World"),
            description = "Reúna seu grupo e retorne aos Reinos Esquecidos em uma história de amizade, traição, sobrevivência e o apelo do poder absoluto.",
            isOwned = false,
            isFeatured = true
        ),
        Game(
            id = "l4d2",
            title = "Left 4 Dead 2",
            price = "R$ 32,99",
            review = "Extremamente Positivas",
            imageResId = R.drawable.game_l4d2,
            bannerResId = R.drawable.game_l4d2,
            tags = listOf("Zombies", "FPS", "Co-op", "Action", "Team-Based"),
            description = "Ambientado no apocalipse zumbi, Left 4 Dead 2 é a sequência muito esperada do premiado Left 4 Dead, o jogo cooperativo número 1.",
            isOwned = true,
            isInstalled = true,
            hoursPlayed = "230 hrs",
            becausePlayed = true
        ),
        Game(
            id = "portal2",
            title = "Portal 2",
            price = "R$ 32,99",
            review = "Extremamente Positivas",
            imageResId = R.drawable.game_portal2,
            bannerResId = R.drawable.game_portal2,
            tags = listOf("Puzzle", "Sci-Fi", "Co-op", "Action", "Singleplayer"),
            description = "Portal 2 cria uma fórmula vencedora de jogabilidade inovadora, história envolvente e música cativante que rendeu ao original mais de 70 prêmios.",
            isOwned = true,
            isInstalled = true,
            hoursPlayed = "45 hrs"
        ),
        Game(
            id = "re4",
            title = "Resident Evil 4 Remake",
            price = "R$ 139,30",
            originalPrice = "R$ 199,00",
            discountPercent = "-30%",
            review = "Extremamente Positivas",
            imageResId = R.drawable.game_re4,
            bannerResId = R.drawable.game_re4,
            tags = listOf("Horror", "Survival", "Zombies", "Action", "Singleplayer"),
            description = "A sobrevivência é apenas o começo. Leon S. Kennedy é enviado em uma missão para resgatar a filha do presidente dos Estados Unidos em um vilarejo europeu isolado.",
            isOwned = true,
            isInstalled = false,
            hoursPlayed = "32 hrs",
            isDiscounted = true,
            isFeatured = true
        ),
        Game(
            id = "dayz",
            title = "DayZ",
            price = "R$ 149,99",
            review = "Ligeiramente Positivas",
            imageResId = R.drawable.game_dayz,
            bannerResId = R.drawable.game_dayz,
            tags = listOf("Zombies", "Survival", "Open World", "Multiplayer", "FPS"),
            description = "Até onde você iria para sobreviver em um mundo pós-apocalíptico infectado por zumbis e habitado por sobreviventes imprevisíveis?",
            isOwned = true,
            isInstalled = true,
            hoursPlayed = "180 hrs",
            becausePlayed = true
        ),
        Game(
            id = "gtav",
            title = "Grand Theft Auto V",
            price = "R$ 82,42",
            originalPrice = "R$ 149,90",
            discountPercent = "-45%",
            review = "Muito Positivas",
            imageResId = R.drawable.game_gtav,
            bannerResId = R.drawable.game_gtav,
            tags = listOf("Open World", "Action", "Multiplayer", "Racing", "Crime"),
            description = "Quando um jovem golpista, um assaltante de bancos aposentado e um psicopata aterrorizante se envolvem com os criminosos mais assustadores do submundo.",
            isOwned = true,
            isInstalled = false,
            hoursPlayed = "420 hrs",
            isDiscounted = true
        ),
        Game(
            id = "rdr2",
            title = "Red Dead Redemption 2",
            price = "R$ 119,96",
            originalPrice = "R$ 299,90",
            discountPercent = "-60%",
            review = "Extremamente Positivas",
            imageResId = R.drawable.game_rdr2,
            bannerResId = R.drawable.game_rdr2,
            tags = listOf("Open World", "Action", "RPG", "Singleplayer", "Multiplayer"),
            description = "Arthur Morgan e a gangue Van der Linde são fugitivos procurados. Com agentes federais e os melhores caçadores de recompensas em seu encalço.",
            isOwned = true,
            isInstalled = true,
            hoursPlayed = "210 hrs",
            isDiscounted = true,
            isFeatured = true
        ),
        Game(
            id = "witcher3",
            title = "The Witcher 3: Wild Hunt",
            price = "R$ 32,49",
            originalPrice = "R$ 129,99",
            discountPercent = "-75%",
            review = "Extremamente Positivas",
            imageResId = R.drawable.game_witcher3,
            bannerResId = R.drawable.game_witcher3,
            tags = listOf("RPG", "Open World", "Action", "Fantasy", "Singleplayer"),
            description = "Você é Geralt de Rívia, um caçador de monstros mercenário. À sua frente está um continente devastado pela guerra e infestado de monstros.",
            isOwned = true,
            isInstalled = true,
            hoursPlayed = "195 hrs",
            isDiscounted = true
        ),
        Game(
            id = "eafc25",
            title = "EA SPORTS FC™ 25",
            price = "R$ 359,00",
            review = "Ligeiramente Positivas",
            imageResId = R.drawable.game_eafc25,
            bannerResId = R.drawable.game_eafc25,
            tags = listOf("Sports", "Competitive", "Simulation", "Multiplayer"),
            description = "Sinta o jogo com EA SPORTS FC™ 25, apresentando os maiores torneios, clubes e astros do futebol mundial.",
            isOwned = false
        ),
        Game(
            id = "sf6",
            title = "Street Fighter 6",
            price = "R$ 164,34",
            originalPrice = "R$ 249,00",
            discountPercent = "-34%",
            review = "Muito Positivas",
            imageResId = R.drawable.game_sf6,
            bannerResId = R.drawable.game_sf6,
            tags = listOf("Fighting", "Competitive", "Action", "Multiplayer"),
            description = "O mais novo desafiante da Capcom chegou! Street Fighter™ 6 representa a próxima evolução da série de jogos de luta.",
            isOwned = false,
            isDiscounted = true
        ),
        Game(
            id = "tekken8",
            title = "TEKKEN 8",
            price = "R$ 269,90",
            review = "Muito Positivas",
            imageResId = R.drawable.game_tekken8,
            bannerResId = R.drawable.game_tekken8,
            tags = listOf("Fighting", "Competitive", "Action", "Multiplayer"),
            description = "Prepare-se para o próximo capítulo da lendária franquia de jogos de luta. O conflito entre as famílias Mishima e Kazama continua.",
            isOwned = false
        ),
        Game(
            id = "mk1",
            title = "Mortal Kombat 1",
            price = "R$ 119,60",
            originalPrice = "R$ 299,00",
            discountPercent = "-60%",
            review = "Ligeiramente Positivas",
            imageResId = R.drawable.game_mk1,
            bannerResId = R.drawable.game_mk1,
            tags = listOf("Fighting", "Action", "Competitive", "Multiplayer"),
            description = "Descubra um Universo Mortal Kombat renascido criado pelo Deus do Fogo Liu Kang. Mortal Kombat 1 inaugura uma nova era!",
            isOwned = false,
            isDiscounted = true
        ),
        Game(
            id = "phasmo",
            title = "Phasmophobia",
            price = "R$ 41,99",
            review = "Extremamente Positivas",
            imageResId = R.drawable.game_phasmo,
            bannerResId = R.drawable.game_phasmo,
            tags = listOf("Horror", "Co-op", "Survival", "Multiplayer"),
            description = "Phasmophobia é um terror psicológico cooperativo online para 4 jogadores. Atividade paranormal está em alta!",
            isOwned = true,
            isInstalled = true,
            hoursPlayed = "76 hrs",
            becausePlayed = true
        ),
        Game(
            id = "dbd",
            title = "Dead by Daylight",
            price = "R$ 23,99",
            originalPrice = "R$ 59,99",
            discountPercent = "-60%",
            review = "Muito Positivas",
            imageResId = R.drawable.game_dbd,
            bannerResId = R.drawable.game_dbd,
            tags = listOf("Horror", "Survival", "Team-Based", "Multiplayer", "Competitive"),
            description = "Dead by Daylight é um jogo de terror multijogador (4vs1) em que um jogador assume o papel do Assassino cruel.",
            isOwned = true,
            isInstalled = false,
            hoursPlayed = "105 hrs",
            isDiscounted = true
        ),
        Game(
            id = "rust",
            title = "Rust",
            price = "R$ 103,49",
            review = "Muito Positivas",
            imageResId = R.drawable.game_rust,
            bannerResId = R.drawable.game_rust,
            tags = listOf("Survival", "Open World", "Multiplayer", "Crafting", "Action"),
            description = "O único objetivo em Rust é sobreviver. Supere lutas como a fome, a sede e o frio. Construa um abrigo e proteja-se.",
            isOwned = true,
            isInstalled = false,
            hoursPlayed = "290 hrs"
        ),
        Game(
            id = "terraria",
            title = "Terraria",
            price = "R$ 32,99",
            review = "Extremamente Positivas",
            imageResId = R.drawable.game_terraria,
            bannerResId = R.drawable.game_terraria,
            tags = listOf("Survival", "Open World", "Crafting", "Indie", "Co-op"),
            description = "Escave, lute, explore, construa! Nada é impossível neste jogo de aventura repleto de ação.",
            isOwned = true,
            isInstalled = true,
            hoursPlayed = "160 hrs"
        ),
        Game(
            id = "stardew",
            title = "Stardew Valley",
            price = "R$ 24,99",
            review = "Extremamente Positivas",
            imageResId = R.drawable.game_stardew,
            bannerResId = R.drawable.game_stardew,
            tags = listOf("Casual", "Simulation", "RPG", "Co-op", "Indie"),
            description = "Você herdou a antiga fazenda do seu avô em Stardew Valley. Armado com ferramentas de segunda mão e algumas moedas.",
            isOwned = true,
            isInstalled = true,
            hoursPlayed = "112 hrs"
        ),
        Game(
            id = "palworld",
            title = "Palworld",
            price = "R$ 88,99",
            review = "Muito Positivas",
            imageResId = R.drawable.game_palworld,
            bannerResId = R.drawable.game_palworld,
            tags = listOf("Open World", "Survival", "Crafting", "Multiplayer", "Action"),
            description = "Colecione criaturas misteriosas chamadas 'Pals' neste jogo de sobrevivência e criação em mundo aberto.",
            isOwned = false
        ),
        Game(
            id = "helldivers2",
            title = "HELLDIVERS™ 2",
            price = "R$ 199,50",
            review = "Muito Positivas",
            imageResId = R.drawable.game_helldivers2,
            bannerResId = R.drawable.game_helldivers2,
            tags = listOf("Action", "Co-op", "Sci-Fi", "Team-Based", "FPS"),
            description = "A última linha de ataque da galáxia. Aliste-se aos Helldivers e junte-se à luta pela Liberdade numa galáxia hostil.",
            isOwned = true,
            isInstalled = true,
            hoursPlayed = "98 hrs",
            isFeatured = true,
            becausePlayed = true
        ),
        Game(
            id = "mh_wilds",
            title = "Monster Hunter Wilds",
            price = "R$ 279,00",
            review = "Muito Positivas",
            imageResId = R.drawable.game_mh_wilds,
            bannerResId = R.drawable.game_mh_wilds,
            tags = listOf("Action", "RPG", "Co-op", "Open World", "Multiplayer"),
            description = "Força desenfreada da natureza e monstros selvagens impiedosos. A experiência definitiva de caça aguarda você.",
            isOwned = false,
            isFeatured = true
        ),
        Game(
            id = "hollow_knight",
            title = "Hollow Knight",
            price = "R$ 46,99",
            review = "Extremamente Positivas",
            imageResId = R.drawable.game_hollow_knight,
            bannerResId = R.drawable.game_hollow_knight,
            tags = listOf("Indie", "Action", "Platformer", "Dark Fantasy", "Singleplayer"),
            description = "Forje seu próprio caminho em Hollow Knight! Uma aventura épica através de um vasto reino arruinado de insetos e heróis.",
            isOwned = true,
            isInstalled = true,
            hoursPlayed = "54 hrs"
        ),
        Game(
            id = "hades",
            title = "Hades",
            price = "R$ 73,99",
            review = "Extremamente Positivas",
            imageResId = R.drawable.game_hades,
            bannerResId = R.drawable.game_hades,
            tags = listOf("Action", "Indie", "RPG", "Rogue-like", "Singleplayer"),
            description = "Desafie o deus dos mortos enquanto você batalha para sair do Submundo neste jogo de masmorras rogue-like dos criadores de Bastion.",
            isOwned = true,
            isInstalled = true,
            hoursPlayed = "72 hrs"
        ),
        Game(
            id = "hades2",
            title = "Hades II",
            price = "R$ 88,99",
            review = "Extremamente Positivas",
            imageResId = R.drawable.game_hades2,
            bannerResId = R.drawable.game_hades2,
            tags = listOf("Action", "Indie", "RPG", "Rogue-like", "Singleplayer"),
            description = "Batalhe além do Submundo usando magia negra para enfrentar o Titã do Tempo na sequência do aclamado jogo rogue-like.",
            isOwned = false
        ),
        Game(
            id = "wukong",
            title = "Black Myth: Wukong",
            price = "R$ 229,90",
            review = "Extremamente Positivas",
            imageResId = R.drawable.game_num31,
            bannerResId = R.drawable.game_num31,
            tags = listOf("Action", "RPG", "Fantasy", "Singleplayer", "Open World"),
            description = "Black Myth: Wukong é um RPG de ação enraizado na mitologia chinesa. Você partirá como o Destinado a enfrentar os desafios.",
            isOwned = false,
            isFeatured = true
        ),
        Game(
            id = "gow_rag",
            title = "God of War Ragnarök",
            price = "R$ 249,90",
            review = "Muito Positivas",
            imageResId = R.drawable.game_gow_rag,
            bannerResId = R.drawable.game_gow_rag,
            tags = listOf("Action", "Open World", "Story", "Singleplayer", "RPG"),
            description = "Embarque numa jornada mítica em busca de respostas e aliados antes que o Ragnarök aconteça.",
            isOwned = true,
            isInstalled = true,
            hoursPlayed = "65 hrs"
        ),
        Game(
            id = "spiderman",
            title = "Marvel's Spider-Man Remastered",
            price = "R$ 149,94",
            originalPrice = "R$ 249,90",
            discountPercent = "-40%",
            review = "Extremamente Positivas",
            imageResId = R.drawable.game_spiderman,
            bannerResId = R.drawable.game_spiderman,
            tags = listOf("Action", "Open World", "Superhero", "Singleplayer"),
            description = "Desenvolvido pela Insomniac Games, jogue como um Peter Parker experiente que combate grandes crimes em Nova York.",
            isOwned = true,
            isInstalled = false,
            hoursPlayed = "40 hrs",
            isDiscounted = true
        ),
        Game(
            id = "horizon",
            title = "Horizon Zero Dawn™ Complete Edition",
            price = "R$ 49,97",
            originalPrice = "R$ 199,90",
            discountPercent = "-75%",
            review = "Extremamente Positivas",
            imageResId = R.drawable.game_horizon,
            bannerResId = R.drawable.game_horizon,
            tags = listOf("Open World", "Action", "Sci-Fi", "RPG", "Singleplayer"),
            description = "Viva a lendária jornada de Aloy para desvendar os mistérios de uma Terra do futuro governada por máquinas mortais.",
            isOwned = true,
            isInstalled = false,
            hoursPlayed = "55 hrs",
            isDiscounted = true
        ),
        Game(
            id = "forza5",
            title = "Forza Horizon 5",
            price = "R$ 124,50",
            originalPrice = "R$ 249,00",
            discountPercent = "-50%",
            review = "Muito Positivas",
            imageResId = R.drawable.game_forza5,
            bannerResId = R.drawable.game_forza5,
            tags = listOf("Racing", "Open World", "Sports", "Multiplayer"),
            description = "Sua Maior Aventura Horizon te espera! Explore as paisagens em constante evolução do México com centenas dos melhores carros do mundo.",
            isOwned = false,
            isDiscounted = true
        ),
        Game(
            id = "assetto",
            title = "Assetto Corsa",
            price = "R$ 11,99",
            originalPrice = "R$ 59,99",
            discountPercent = "-80%",
            review = "Extremamente Positivas",
            imageResId = R.drawable.game_assetto,
            bannerResId = R.drawable.game_assetto,
            tags = listOf("Racing", "Simulation", "Driving", "Multiplayer"),
            description = "Assetto Corsa apresenta um mecanismo gráfico DirectX 11 avançado que oferece um ambiente imersivo com física ultra-realista.",
            isOwned = false,
            isDiscounted = true
        ),
        Game(
            id = "ets2",
            title = "Euro Truck Simulator 2",
            price = "R$ 15,49",
            originalPrice = "R$ 61,99",
            discountPercent = "-75%",
            review = "Extremamente Positivas",
            imageResId = R.drawable.game_ets2,
            bannerResId = R.drawable.game_ets2,
            tags = listOf("Simulation", "Driving", "Open World", "Relaxing"),
            description = "Viaje pela Europa como o rei da estrada, um caminhoneiro que entrega cargas importantes através de distâncias impressionantes!",
            isOwned = true,
            isInstalled = true,
            hoursPlayed = "310 hrs",
            isDiscounted = true
        ),
        Game(
            id = "cities",
            title = "Cities: Skylines",
            price = "R$ 31,49",
            originalPrice = "R$ 125,99",
            discountPercent = "-75%",
            review = "Muito Positivas",
            imageResId = R.drawable.game_num23,
            bannerResId = R.drawable.game_num23,
            tags = listOf("Simulation", "Strategy", "City Builder", "Singleplayer"),
            description = "Cities: Skylines é uma versão moderna da simulação de cidade clássica. O jogo introduz novos elementos de jogabilidade para realizar a emoção de construir.",
            isOwned = true,
            isInstalled = false,
            hoursPlayed = "80 hrs",
            isDiscounted = true
        ),
        Game(
            id = "civ6",
            title = "Sid Meier's Civilization VI",
            price = "R$ 12,90",
            originalPrice = "R$ 129,00",
            discountPercent = "-90%",
            review = "Muito Positivas",
            imageResId = R.drawable.game_civ6,
            bannerResId = R.drawable.game_civ6,
            tags = listOf("Strategy", "Turn-Based", "Historical", "Multiplayer"),
            description = "Civilization VI oferece novas formas de se engajar com seu mundo: cidades agora se expandem fisicamente pelo mapa, pesquisas ativas destravam novidades.",
            isOwned = true,
            isInstalled = false,
            hoursPlayed = "145 hrs",
            isDiscounted = true
        ),
        Game(
            id = "hoi4",
            title = "Hearts of Iron IV",
            price = "R$ 49,99",
            originalPrice = "R$ 199,99",
            discountPercent = "-75%",
            review = "Muito Positivas",
            imageResId = R.drawable.game_hoi4,
            bannerResId = R.drawable.game_hoi4,
            tags = listOf("Strategy", "WW2", "Military", "Simulation"),
            description = "Assuma o comando da maior máquina de guerra da história em Hearts of Iron IV, um jogo de estratégia em grande escala.",
            isOwned = false,
            isDiscounted = true
        ),
        Game(
            id = "subnautica",
            title = "Subnautica",
            price = "R$ 32,99",
            originalPrice = "R$ 99,99",
            discountPercent = "-67%",
            review = "Extremamente Positivas",
            imageResId = R.drawable.game_subnautica,
            bannerResId = R.drawable.game_subnautica,
            tags = listOf("Survival", "Open World", "Sci-Fi", "Exploration"),
            description = "Mergulhe nas profundezas de um mundo alienígena subaquático cheio de maravilhas e perigos.",
            isOwned = true,
            isInstalled = true,
            hoursPlayed = "48 hrs",
            isDiscounted = true
        ),
        Game(
            id = "the_forest",
            title = "The Forest",
            price = "R$ 9,49",
            originalPrice = "R$ 37,99",
            discountPercent = "-75%",
            review = "Extremamente Positivas",
            imageResId = R.drawable.game_the_forest,
            bannerResId = R.drawable.game_the_forest,
            tags = listOf("Survival", "Horror", "Co-op", "Crafting"),
            description = "Como o único sobrevivente de uma queda de avião de passageiros, você se encontra em uma floresta misteriosa lutando para se manter vivo.",
            isOwned = true,
            isInstalled = false,
            hoursPlayed = "62 hrs",
            isDiscounted = true
        ),
        Game(
            id = "sons_forest",
            title = "Sons Of The Forest",
            price = "R$ 88,99",
            review = "Muito Positivas",
            imageResId = R.drawable.game_sons_forest,
            bannerResId = R.drawable.game_sons_forest,
            tags = listOf("Survival", "Horror", "Co-op", "Open World"),
            description = "Enviado para encontrar um bilionário desaparecido em uma ilha remota, você se vê em um inferno infestado de canibais.",
            isOwned = false
        ),
        Game(
            id = "dying_light2",
            title = "Dying Light 2 Stay Human",
            price = "R$ 119,60",
            originalPrice = "R$ 299,00",
            discountPercent = "-60%",
            review = "Muito Positivas",
            imageResId = R.drawable.game_dying_light2,
            bannerResId = R.drawable.game_dying_light2,
            tags = listOf("Zombies", "Open World", "Action", "Parkour", "Survival"),
            description = "O vírus venceu e a civilização voltou para a Idade das Trevas. A Cidade, um dos últimos assentamentos humanos, está à beira do colapso.",
            isOwned = false,
            isDiscounted = true
        ),
        Game(
            id = "dead_island2",
            title = "Dead Island 2",
            price = "R$ 149,50",
            originalPrice = "R$ 299,00",
            discountPercent = "-50%",
            review = "Muito Positivas",
            imageResId = R.drawable.game_dead_island2,
            bannerResId = R.drawable.game_dead_island2,
            tags = listOf("Zombies", "Action", "Co-op", "Gore", "Survival"),
            description = "Um vírus deadly se espalha por Los Angeles, transformando os moradores em zumbis. A cidade está em quarentena.",
            isOwned = false,
            isDiscounted = true
        ),
        Game(
            id = "re_village",
            title = "Resident Evil Village",
            price = "R$ 55,96",
            originalPrice = "R$ 139,90",
            discountPercent = "-60%",
            review = "Extremamente Positivas",
            imageResId = R.drawable.game_re_village,
            bannerResId = R.drawable.game_re_village,
            tags = listOf("Horror", "Survival", "Zombies", "Action"),
            description = "Experimente o terror de sobrevivência como nunca antes no oitavo grande capítulo da lendária franquia Resident Evil.",
            isOwned = true,
            isInstalled = false,
            hoursPlayed = "28 hrs",
            isDiscounted = true
        ),
        Game(
            id = "re2",
            title = "Resident Evil 2 Remake",
            price = "R$ 34,97",
            originalPrice = "R$ 139,90",
            discountPercent = "-75%",
            review = "Extremamente Positivas",
            imageResId = R.drawable.game_re2,
            bannerResId = R.drawable.game_re2,
            tags = listOf("Horror", "Zombies", "Survival", "Action"),
            description = "Lançado originalmente em 1998, o clássico jogo de survival horror retorna completamente reconstruído.",
            isOwned = true,
            isInstalled = true,
            hoursPlayed = "35 hrs",
            isDiscounted = true
        ),
        Game(
            id = "hl2",
            title = "Half-Life 2",
            price = "R$ 32,99",
            review = "Extremamente Positivas",
            imageResId = R.drawable.game_hl2,
            bannerResId = R.drawable.game_hl2,
            tags = listOf("FPS", "Sci-Fi", "Story", "Action", "Singleplayer"),
            description = "Pegando o pé de cabra do cientista Gordon Freeman, você se encontra em uma Terra infestada de alienígenas.",
            isOwned = true,
            isInstalled = true,
            hoursPlayed = "90 hrs"
        ),
        Game(
            id = "alyx",
            title = "Half-Life: Alyx",
            price = "R$ 54,39",
            originalPrice = "R$ 162,00",
            discountPercent = "-66%",
            review = "Extremamente Positivas",
            imageResId = R.drawable.game_num54,
            bannerResId = R.drawable.game_num54,
            tags = listOf("VR", "FPS", "Sci-Fi", "Horror", "Action"),
            description = "Half-Life: Alyx é o retorno em realidade virtual da Valve à série Half-Life. É a história de uma luta impossível contra uma raça alienígena.",
            isOwned = true,
            isInstalled = false,
            hoursPlayed = "18 hrs",
            isDiscounted = true
        ),
        Game(
            id = "payday2",
            title = "PAYDAY 2",
            price = "R$ 4,99",
            originalPrice = "R$ 24,99",
            discountPercent = "-80%",
            review = "Extremamente Positivas",
            imageResId = R.drawable.game_payday2,
            bannerResId = R.drawable.game_payday2,
            tags = listOf("FPS", "Co-op", "Team-Based", "Action", "Crime"),
            description = "PAYDAY 2 é um jogo de tiro cooperativo para quatro jogadores repleto de ação que permite que os jogadores coloquem a máscara do lendário Payday Crew.",
            isOwned = true,
            isInstalled = true,
            hoursPlayed = "140 hrs",
            isDiscounted = true
        ),
        Game(
            id = "r6_siege",
            title = "Tom Clancy's Rainbow Six® Siege",
            price = "R$ 23,99",
            originalPrice = "R$ 59,99",
            discountPercent = "-60%",
            review = "Muito Positivas",
            imageResId = R.drawable.game_r6_siege,
            bannerResId = R.drawable.game_r6_siege,
            tags = listOf("FPS", "Competitive", "Tactical", "Team-Based"),
            description = "Domine a arte da destruição e das engenharias em Tom Clancy's Rainbow Six Siege. Enfrente combates intensos de proximidade.",
            isOwned = true,
            isInstalled = false,
            hoursPlayed = "260 hrs",
            isDiscounted = true
        ),
        Game(
            id = "arma3",
            title = "Arma 3",
            price = "R$ 24,99",
            originalPrice = "R$ 99,99",
            discountPercent = "-75%",
            review = "Muito Positivas",
            imageResId = R.drawable.game_arma3,
            bannerResId = R.drawable.game_arma3,
            tags = listOf("Tactical", "FPS", "Simulation", "Multiplayer"),
            description = "Experimente a jogabilidade de combate militar autêntica em um enorme sandbox militar em mundo aberto.",
            isOwned = true,
            isInstalled = false,
            hoursPlayed = "110 hrs",
            isDiscounted = true
        ),
        Game(
            id = "squad",
            title = "Squad",
            price = "R$ 95,40",
            originalPrice = "R$ 159,00",
            discountPercent = "-40%",
            review = "Muito Positivas",
            imageResId = R.drawable.game_squad,
            bannerResId = R.drawable.game_squad,
            tags = listOf("Tactical", "FPS", "Team-Based", "Military"),
            description = "Squad é um jogo de tiro em primeira pessoa combinado de 50 contra 50 que visa capturar o realismo do combate por meio da comunicação.",
            isOwned = false,
            isDiscounted = true
        ),
        Game(
            id = "warthunder",
            title = "War Thunder",
            price = "Grátis",
            review = "Muito Positivas",
            imageResId = R.drawable.game_warthunder,
            bannerResId = R.drawable.game_warthunder,
            tags = listOf("Military", "Simulation", "Action", "Multiplayer"),
            description = "War Thunder é o jogo MMO militar gratuito mais completo dedicado a aviação, veículos blindados e navios de guerra.",
            isOwned = true,
            isInstalled = true,
            hoursPlayed = "200 hrs"
        ),
        Game(
            id = "wot",
            title = "World of Tanks",
            price = "Grátis",
            review = "Muito Positivas",
            imageResId = R.drawable.game_wot,
            bannerResId = R.drawable.game_wot,
            tags = listOf("Military", "Action", "Team-Based", "Multiplayer"),
            description = "Entre no jogo de tiro em equipe gratuito com um arsenal em constante expansão de veículos históricos, gráficos impressionantes.",
            isOwned = false
        ),
        Game(
            id = "sea_of_thieves",
            title = "Sea of Thieves 2024 Edition",
            price = "R$ 44,99",
            originalPrice = "R$ 89,99",
            discountPercent = "-50%",
            review = "Muito Positivas",
            imageResId = R.drawable.game_sea_of_thieves,
            bannerResId = R.drawable.game_sea_of_thieves,
            tags = listOf("Open World", "Co-op", "Multiplayer", "Action"),
            description = "Sea of Thieves oferece a experiência pirata essencial, repleta de navegação e exploração, lutas e saques, solução de enigmas.",
            isOwned = true,
            isInstalled = false,
            hoursPlayed = "75 hrs",
            isDiscounted = true
        )
    )

    fun getGameById(id: String): Game? = allGames.find { it.id == id }

    fun getGamesByCategoryTag(tag: String): List<Game> {
        if (tag.equals("Todos", ignoreCase = true) || tag.isBlank()) {
            return allGames
        }
        return allGames.filter { game ->
            game.tags.any { it.equals(tag, ignoreCase = true) }
        }
    }

    fun getFeaturedGames(): List<Game> = allGames.filter { it.isFeatured }

    fun getDiscountedGames(): List<Game> = allGames.filter { it.isDiscounted }

    fun getBecausePlayedGames(): List<Game> = allGames.filter { it.becausePlayed }

    fun getOwnedGames(): List<Game> = allGames.filter { it.isOwned }
}
